### PR TITLE
Add Binance Fiat Deposits / Withdraws

### PR DESCRIPTION
**Pull request by weissi1994**
Closes # (issue)

Binance Fiat Deposits / Withdraws were not imported via API

for api reference see https://binance-docs.github.io/apidocs/spot/en/#fiat-endpoints

## Checklist

- [ ] ~~The PR modified the frontend, and updated the [user guide](https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst) to reflect the changes.~~
> No UI changes

### CODE REVIEW

**Comment by yabirgb** [comment]
Hello, thanks for the contribution! There are some tests related to binance that are failing. Also please if you can, please squash the fix commits. We try to avoid this kind of commits in the history

**Comment by weissi1994** [comment]
So far only two binacnce tests are failing, but im not sure why these tests fail, and specifically why the timestamps changed for these test calls :confused:

```
E         Full diff:
E           [
E            call('https://api.binance.com/api/v3/myTrades?fromId=0&limit=1000&symbol=BUSDUSDT&recvWindow=10000&timestamp=1631385422732&signature=ef9d83f99e000f5ee04c96ce041d64e7f14937cffd8a8018dc6c4bb0e705c15e', timeout=(5, 30)),
E         -  call('https://api.binance.com/api/v3/myTrades?fromId=0&limit=1000&symbol=BUSDUSDT&recvWindow=10000&timestamp=1631385422732&signature=ef9d83f99e000f5ee04c96ce041d64e7f14937cffd8a8018dc6c4bb0e705c15e', timeout=(5, 30)),
E         -  call('https://api.binance.com/api/v3/myTrades?fromId=0&limit=1000&symbol=BUSDUSDT&recvWindow=10000&timestamp=1631385422732&signature=ef9d83f99e000f5ee04c96ce041d64e7f14937cffd8a8018dc6c4bb0e705c15e', timeout=(5, 30)),
E         +  call('https://api.binance.com/api/v3/myTrades?fromId=0&limit=1000&symbol=BUSDUSDT&recvWindow=10000&timestamp=1631385423734&signature=6f98d88869b2e9dc3a9d8dcacbc655280acb5ac75e9e0a18e69eca9d24965eb0', timeout=(5, 30)),
E         +  call('https://api.binance.com/api/v3/myTrades?fromId=0&limit=1000&symbol=BUSDUSDT&recvWindow=10000&timestamp=1631385428740&signature=83dfa5346f6629e154319d8c903a9a473d262a92ab13bca5b9c5d5286506f94c', timeout=(5, 30)),
=========================================================================================
FAILED rotkehlchen/tests/exchanges/test_binance.py::test_api_query_list_calls_with_time_delta
FAILED rotkehlchen/tests/exchanges/test_binance.py::test_api_query_retry_on_status_code_429
```

**Review by LefterisJP — CHANGES_REQUESTED** [review]
Hey @dweissengruber. Thank you for the PR. Needs quite a few changes as you are currently duplicating a lot of code.

As for test failures:

- `rotkehlchen/tests/exchanges/test_binance_us.py::test_binanceus_deposits_withdrawals_location` fails since the same changes you made for binance apply to binance us and need the test to be adjusted too.

And also since you edited the mocked responses for binance asset movements all the export CSV history tests also failed since these is more data:
```
FAILED rotkehlchen/tests/api/test_history.py::test_query_history[mocked_price_queries0-ethereum_accounts0-added_exchanges0]
FAILED rotkehlchen/tests/api/test_history.py::test_query_history_timerange[mocked_price_queries0-ethereum_accounts0-added_exchanges0]
FAILED rotkehlchen/tests/api/test_history.py::test_history_export_csv[mocked_price_queries0-ethereum_accounts0-added_exchanges0]
FAILED rotkehlchen/tests/api/test_history.py::test_history_export_csv_errors[mocked_price_queries0-ethereum_accounts0-added_exchanges0]
```

I strongly advice to add a new  binance mocks for fiat deposits only for the new test you wanted to make. Leave the general binance deposit/withdrawal mocks as they were before as it may end up being complicated changing the history tests due to this.

File: rotkehlchen/exchanges/binance.py [hunk 1]
```diff
@@ -1038,12 +1210,44 @@ def query_online_deposits_withdrawals(
...
 
+        for fiat_movement in fiat_deposits:
+            movement = self._deserialize_deposit_fiat_movement(fiat_movement)
+            if movement:
+                movements.append(movement)
+
+        for fiat_movement in fiat_withdraws:
+            movement = self._deserialize_withdraw_fiat_movement(fiat_movement)
+            if movement:
+                movements.append(movement)
```
[the remark this answers is not in the document]
Comment (weissi1994) [reply rotkehlchen/exchanges/binance.py]: not that easy since there is no indication in the api respnse from binance wheter it was a deposit or a withdrawal

File: rotkehlchen/tests/exchanges/test_binance.py [hunk 2]
```diff
@@ -403,10 +406,16 @@ def test_binance_query_deposits_withdrawals_unexpected_data(function_scope_binan
     end_ts = 1508540400  # 2017-10-21 (less than 90 days since `start_ts`)
     binance = function_scope_binance
 
-    def mock_binance_and_query(deposits, withdrawals, expected_warnings_num, expected_errors_num):
+    def mock_binance_and_query(deposits,
```
[the remark this answers is not in the document]
Comment (weissi1994) [reply rotkehlchen/tests/exchanges/test_binance.py]: I reverted my changes to the tests for now, but these tests are still failing locally with the same error :/

```
FAILED rotkehlchen/tests/exchanges/test_binance.py::test_api_query_list_calls_with_time_delta
FAILED rotkehlchen/tests/exchanges/test_binance.py::test_api_query_retry_on_status_code_429
```

File: rotkehlchen/exchanges/binance.py (hunk 1 above)
[the remark this answers is not in the document]
Comment (LefterisJP) [reply rotkehlchen/exchanges/binance.py]: Yeah I see how that can pose a challenge, but here is a way

```python
        for idx, fiat_movement in enumerate(fiat_deposits+fiat_withdraws):
            movement = self._deserialize_fiat_movement(fiat_movement, is_deposit=idx < len(fiat_deposits)
            if movement:
                movements.append(movement)
```

File: rotkehlchen/tests/exchanges/test_binance.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (LefterisJP) [reply rotkehlchen/tests/exchanges/test_binance.py]: I can have a look when review the PR again and run the tests locally on your branch.

**Comment by LefterisJP** [comment]
Btw @weissi1994 for more real-time chat you can also jump on our discord where we have a dedicated dev channel: https://discord.com/invite/aGCxHG7

File: rotkehlchen/exchanges/binance.py (hunk 1 above)
[the remark this answers is not in the document]
Comment (weissi1994) [reply rotkehlchen/exchanges/binance.py]: thx for the snippet :)

File: rotkehlchen/tests/exchanges/test_binance.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (weissi1994) [reply rotkehlchen/tests/exchanges/test_binance.py]: thanks a lot, i have no clue why the timestamps changed for these calls

**Comment by weissi1994** [comment]
ah, nice, then you can just notify me ther when you had time to look into this (my username there is: standalone#6614)

File: rotkehlchen/exchanges/binance.py [hunk 3]
```diff
@@ -847,6 +849,27 @@ def query_online_trade_history(
 
             raw_data.sort(key=lambda x: x['time'])
 
+        # Could also utilize start_ts and end_ts in request
```
Comment (LefterisJP) [inline rotkehlchen/exchanges/binance.py:852]: you have left commented out code here.

File: rotkehlchen/exchanges/binance.py [hunk 4]
```diff
@@ -893,6 +916,92 @@ def query_online_trade_history(
 
         return trades
 
+    def _deserialize_fiat_movement(
+            self,
+            raw_data: Dict[str, Any],
+            transaction_type: Literal['deposit', 'withdrawal', 'buy', 'sell'],
+    ) -> Optional[NamedTuple]:
```
Comment (LefterisJP) [inline rotkehlchen/exchanges/binance.py:923]: The type here is wrong, and this is also why `make lint` fails.

File: rotkehlchen/exchanges/binance.py [hunk 5]
```diff
@@ -893,6 +916,92 @@ def query_online_trade_history(
...
+                asset = asset_from_binance(raw_data['fiatCurrency'])
+                tx_id = get_key_if_has_val(raw_data, 'orderNo')
+                timestamp = deserialize_timestamp_from_binance(raw_data['createTime'])
+                fee = Fee(deserialize_asset_amount(raw_data['totalFee']))
+                link_str = str(tx_id) if tx_id else ''
+                amount = deserialize_asset_amount_force_positive(raw_data['amount'])
+                if transaction_type in ['deposit', 'withdrawal']:
+                    category = (AssetMovementCategory.DEPOSIT
+                                if transaction_type == 'deposit' else
+                                AssetMovementCategory.WITHDRAWAL)
```
Comment (LefterisJP) [inline rotkehlchen/exchanges/binance.py:939]: styling

```suggestion
                    category = (
                        AssetMovementCategory.DEPOSIT
                        if transaction_type == 'deposit' else
                        AssetMovementCategory.WITHDRAWAL
                    )
```

File: rotkehlchen/exchanges/binance.py [hunk 6]
```diff
@@ -893,6 +916,92 @@ def query_online_trade_history(
...
+                        amount=obtain_amount,
+                        rate=rate,
+                        fee=fee,
+                        fee_currency=base_asset,
+                        link=link_str,
+                    )
+
+        except UnknownAsset as e:
+            self.msg_aggregator.add_warning(
+                f'Found {str(self.location)} deposit/withdrawal with unknown asset '
```
Comment (LefterisJP) [inline rotkehlchen/exchanges/binance.py:981]: Here and in the other log messages prepend fiat to deposit/withdrawal 

```suggestion
                f'Found {str(self.location)} fiat deposit/withdrawal with unknown asset '
```

File: rotkehlchen/exchanges/binance.py [hunk 7]
```diff
@@ -995,6 +1110,8 @@ def _api_query_list_within_time_delta(
                 'startTime': from_ts,
                 'endTime': to_ts,
             }
+            if additional_options:
+                options = options | additional_options
```
Comment (LefterisJP) [inline rotkehlchen/exchanges/binance.py:1114]: please don't use pipe operator with dicts.

(1) this is only in python 3.9, we utilize 3.7
(2) it's a bit ambiguous. You would have to know that its' equal to `update`. We try to be explicit in rotki so better use update.

**Review by LefterisJP — COMMENTED** [review]
Left you some more comments. At least when I try to run the tests locally they fail exactly due to the pipe operator and dict.

```
TypeError: unsupported operand type(s) for |: 'dict' and 'dict
```

The python 3.7 requirement is in the docs but its's not enforced anywhere else.  Make sure the venv you setup is python 3.7. (When we update to 3.8 or 3.9) you can update to that.

File: rotkehlchen/exchanges/binance.py (hunk 7 above)
Comment (weissi1994) [reply rotkehlchen/exchanges/binance.py:1114]: sure, wasnt aware of the python3.7 requirement, sorry for that

File: rotkehlchen/exchanges/binance.py (hunk 3 above)
Comment (weissi1994) [reply rotkehlchen/exchanges/binance.py]: this was for the fiat/payments endpoint, was not sure how to integrate the calls into query_online_trade_history

File: rotkehlchen/exchanges/binance.py (hunk 4 above)
Comment (weissi1994) [reply rotkehlchen/exchanges/binance.py]: yeah, wanted to make the deserialize function compatible to the fiat/payments endpoint, how would i type-hint this correctly so that the linter wont complain? since it could also return an instance of Trade when deserializing results from fiat/payments?

Comment (LefterisJP) [reply rotkehlchen/exchanges/binance.py]: That should be `Optional[Union[Trade, AssetMovement]]`

Comment (weissi1994) [reply rotkehlchen/exchanges/binance.py]: thx :)

Comment (weissi1994) [reply rotkehlchen/exchanges/binance.py]: hm :/ linter is still complaining:

```
rotkehlchen/exchanges/binance.py:929: error: Incompatible return value type (got "AssetMovement", expected "Union[Trade, AssetAmount, None]")
Found 3 errors in 1 file (checked 459 source files)
rotkehlchen/exchanges/binance.py:1174: error: Incompatible types in assignment (expression has type "Union[Trade, AssetAmount, None]", variable has type "Optional[AssetMovement]")
```

Comment (LefterisJP) [reply rotkehlchen/exchanges/binance.py]: It's a bit more complicated than that. You would probably need to overload the types? Do you want me to do it to show you how? I can also squash all the merge/fix commits you have.

Comment (weissi1994) [reply rotkehlchen/exchanges/binance.py]: for now i just made a seperate deserialize_fiat_payments function, so that linting passes.
but if you prefer to have them combined, please provide me with an function definition that passes the linter :)

Comment (LefterisJP) [reply rotkehlchen/exchanges/binance.py]: Thank you @dweissengruber! 

There is other examples in the codebase of how one uses mypy to overload function definitions. Also in their docs. I will just do it myself for now so I can show you how it works and you can know for next time. No worries.

(Assuming the problem is what I think it is :rofl: )

Comment (LefterisJP) [reply rotkehlchen/exchanges/binance.py]: Wait wait, so fiat payments come from a different endpoint from what I see.

And the function is not used in your PR at all. In which case different functions make sense. I will try to use it though. Will push on top of your PR.

Comment (LefterisJP) [reply rotkehlchen/exchanges/binance.py]: Added some more commits which should address everything. Tests still need to be written as I saw you removed them. I can take care of it a bit later. Will point you in the code where things needed changing.

File: rotkehlchen/exchanges/binance.py [hunk 8]
```diff
@@ -891,8 +900,170 @@ def query_online_trade_history(
...
             trades.append(trade)
 
+        fiat_payments = self._query_online_fiat_payments(start_ts=start_ts, end_ts=end_ts)
+        if fiat_payments:
+            trades += fiat_payments
+            trades.sort(key=lambda x: x.timestamp)
+
         return trades
 
+    def _query_online_fiat_payments(self, start_ts: Timestamp, end_ts: Timestamp) -> List[Trade]:
```
Comment (LefterisJP) [inline rotkehlchen/exchanges/binance.py:910]: Since fiat orders are essentially trades, I simply added them as an additional step when querying binance trades in a specific time range.

File: rotkehlchen/exchanges/binance.py [hunk 9]
```diff
@@ -891,8 +900,170 @@ def query_online_trade_history(
...
+            self,
+            raw_data: Dict[str, Any],
+            trade_type: TradeType,
+    ) -> Optional[Trade]:
+        """Processes a single deposit/withdrawal from binance and deserializes it
+
+        Can log error/warning and return None if something went wrong at deserialization
+        """
+        try:
+            if 'status' not in raw_data or raw_data['status'] != 'Successful':
```
Comment (LefterisJP) [inline rotkehlchen/exchanges/binance.py:949]: There were errors in deserialization here. Remember. When a buy is made, then the BASE asset is bought with QUOTE asset. When a sell is made then the BASE asset is sold for QUOTE asset. This should now be okay.

Also fiat payments have a price field which is what should be used.

File: rotkehlchen/exchanges/binance.py [hunk 10]
```diff
@@ -891,8 +900,170 @@ def query_online_trade_history(
...
+            trade = self._deserialize_fiat_payment(raw_fiat, trade_type=trade_type)
+            if trade:
+                trades.append(trade)
+
+        return trades
+
+    def _deserialize_fiat_payment(
+            self,
+            raw_data: Dict[str, Any],
+            trade_type: TradeType,
```
Comment (LefterisJP) [inline rotkehlchen/exchanges/binance.py:942]: Passing the trade type directly as an enum here

File: rotkehlchen/exchanges/binance.py [hunk 11]
```diff
@@ -891,8 +900,170 @@ def query_online_trade_history(
...
+                asset_movement=raw_data,
+                error=msg,
+            )
+
+        return None
+
+    def _deserialize_fiat_movement(
+            self,
+            raw_data: Dict[str, Any],
+            category: AssetMovementCategory,
```
Comment (LefterisJP) [inline rotkehlchen/exchanges/binance.py:1009]: passing the category directly as an enum here

File: rotkehlchen/exchanges/binance.py [hunk 12]
```diff
@@ -1038,12 +1217,37 @@ def query_online_deposits_withdrawals(
         )
         log.debug(f'{self.name} withdraw history result', results_num=len(withdraws))
 
+        fiat_deposits = self._api_query_list_within_time_delta(
+            start_ts=Timestamp(0),
+            end_ts=end_ts,
+            time_delta=API_TIME_INTERVAL_CONSTRAINT_TS,
+            api_type='sapi',
+            method='fiat/orders',
+            additional_options={'transactionType': 0},
```
Comment (LefterisJP) [inline rotkehlchen/exchanges/binance.py:1226]: This was `transaction_type` but when checking their docs it's `transactionType` https://binance-docs.github.io/apidocs/spot/en/#get-fiat-deposit-withdraw-history-user_data

**Comment by LefterisJP** [comment]
I will also adjust tests soon as I find some time.

**Review by LefterisJP — APPROVED** [review]
Okay tests passed. There is some tests missing but will make an issue for them to be done in another PR later.
